version: "3.9"
services:
  redis:
    ports:
      - 127.0.0.1:6379:6379
    image: redis

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
     - 8080:80
    volumes:
     - ./frontend:/usr/share/nginx/html:rw
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
     - SERVICE_ADDR=127.0.0.1

  ss_position:
    build: backend/SS_Position/.
    ports:
      - 8081:8081
    links:
      - redis
      - ss_maploader
  
  ss_maploader:
    build: backend/SS_MapLoader/.
    ports:
      - 8082:8082

  ss_manager:
    build: backend/SS_Manager/.
    ports:
      - 8083:8083
      - 8084:8084
  
  ss_itemskeeper:
    build: backend/SS_ItemsKeeper/.
    ports:
      - 8085:8085

  ss_inventory:
    build: backend/SS_Inventory/.
    ports:
      - 8086:8086
